// This file has been autogenerated.

var profile = require('../../../lib/util/profile');

exports.getMockedProfile = function () {
  var newProfile = new profile.Profile();

  newProfile.addSubscription(new profile.Subscription({
    id: '04db7ed3-6ed9-4861-8b22-7c0c0c98490b',
    name: 'AAPT Cache10',
    user: {
      name: 'user@domain.example',
      type: 'user'
    },
    tenantId: '72f988bf-86f1-41af-91ab-2d7cd011db47',
    registeredProviders: [],
    isDefault: true
  }, newProfile.environments['AzureCloud']));

  return newProfile;
};

exports.setEnvironment = function() {
  process.env['AZURE_ARM_TEST_LOCATION'] = 'West US';
  process.env['AZURE_ARM_TEST_RESOURCE_GROUP'] = 'xplatTestCacheRG';
};

exports.scopes = [[function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/04db7ed3-6ed9-4861-8b22-7c0c0c98490b/resourceGroups/xplatTestCacheRG/providers/Microsoft.Cache/Redis/xplatTestCache2861?api-version=2015-03-01')
  .reply(404, "{\"error\":{\"code\":\"ResourceNotFound\",\"message\":\"The Resource 'Microsoft.Cache/Redis/xplatTestCache2861' under resource group 'xplatTestCacheRG' was not found.\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-failure-cause': 'gateway',
  'x-ms-request-id': '9cda9d0c-ed71-4648-bd62-35139d8b2b9a',
  'x-ms-correlation-request-id': '9cda9d0c-ed71-4648-bd62-35139d8b2b9a',
  'x-ms-routing-request-id': 'WESTUS:20150820T002332Z:9cda9d0c-ed71-4648-bd62-35139d8b2b9a',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Thu, 20 Aug 2015 00:23:32 GMT',
  connection: 'close',
  'content-length': '160' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/04db7ed3-6ed9-4861-8b22-7c0c0c98490b/resourceGroups/xplatTestCacheRG/providers/Microsoft.Cache/Redis/xplatTestCache2861?api-version=2015-03-01')
  .reply(404, "{\"error\":{\"code\":\"ResourceNotFound\",\"message\":\"The Resource 'Microsoft.Cache/Redis/xplatTestCache2861' under resource group 'xplatTestCacheRG' was not found.\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-failure-cause': 'gateway',
  'x-ms-request-id': '9cda9d0c-ed71-4648-bd62-35139d8b2b9a',
  'x-ms-correlation-request-id': '9cda9d0c-ed71-4648-bd62-35139d8b2b9a',
  'x-ms-routing-request-id': 'WESTUS:20150820T002332Z:9cda9d0c-ed71-4648-bd62-35139d8b2b9a',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Thu, 20 Aug 2015 00:23:32 GMT',
  connection: 'close',
  'content-length': '160' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/04db7ed3-6ed9-4861-8b22-7c0c0c98490b/resourceGroups/xplatTestCacheRG/providers/Microsoft.Cache/Redis/xplatTestCache2861?api-version=2015-03-01', '*')
  .reply(201, "{\"id\":\"/subscriptions/04db7ed3-6ed9-4861-8b22-7c0c0c98490b/resourceGroups/xplatTestCacheRG/providers/Microsoft.Cache/Redis/xplatTestCache2861\",\"location\":\"West US\",\"name\":\"xplatTestCache2861\",\"type\":\"Microsoft.Cache/Redis\",\"tags\":{},\"properties\":{\"provisioningState\":\"Creating\",\"redisVersion\":\"3.0\",\"sku\":{\"name\":\"Standard\",\"family\":\"C\",\"capacity\":1},\"enableNonSslPort\":false,\"redisConfiguration\":{\"maxmemory-policy\":\"allkeys-lru\"},\"accessKeys\":{\"primaryKey\":\"licxmVWwPCiuVHB3hoV9JFvle9HASoQG5SR093fSrNU=\",\"secondaryKey\":\"YiLgMoTnp3hlaqphprwEyeDspbGjkfnpRDB2TTmK6HQ=\"},\"hostName\":\"xplatTestCache2861.redis.cache.windows.net\",\"port\":6379,\"sslPort\":6380}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '653',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  location: 'https://prod-rp-wus.cacheinfra.windows.net:10225/subscriptions/04db7ed3-6ed9-4861-8b22-7c0c0c98490b/resourceGroups/xplatTestCacheRG/providers/Microsoft.Cache/Redis/xplatTestCache2861',
  'x-ms-request-id': 'c7cac79d-667a-4d0a-b1be-6fe175ad7a3d',
  'x-rp-server-mvid': 'af670903-1b42-4933-b84c-636f2d204d89',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-writes': '1197',
  'x-ms-correlation-request-id': 'ee1c0c18-b83e-4351-a5a0-bb9b2a02fa6b',
  'x-ms-routing-request-id': 'WESTUS:20150820T002333Z:ee1c0c18-b83e-4351-a5a0-bb9b2a02fa6b',
  date: 'Thu, 20 Aug 2015 00:23:33 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/04db7ed3-6ed9-4861-8b22-7c0c0c98490b/resourceGroups/xplatTestCacheRG/providers/Microsoft.Cache/Redis/xplatTestCache2861?api-version=2015-03-01', '*')
  .reply(201, "{\"id\":\"/subscriptions/04db7ed3-6ed9-4861-8b22-7c0c0c98490b/resourceGroups/xplatTestCacheRG/providers/Microsoft.Cache/Redis/xplatTestCache2861\",\"location\":\"West US\",\"name\":\"xplatTestCache2861\",\"type\":\"Microsoft.Cache/Redis\",\"tags\":{},\"properties\":{\"provisioningState\":\"Creating\",\"redisVersion\":\"3.0\",\"sku\":{\"name\":\"Standard\",\"family\":\"C\",\"capacity\":1},\"enableNonSslPort\":false,\"redisConfiguration\":{\"maxmemory-policy\":\"allkeys-lru\"},\"accessKeys\":{\"primaryKey\":\"licxmVWwPCiuVHB3hoV9JFvle9HASoQG5SR093fSrNU=\",\"secondaryKey\":\"YiLgMoTnp3hlaqphprwEyeDspbGjkfnpRDB2TTmK6HQ=\"},\"hostName\":\"xplatTestCache2861.redis.cache.windows.net\",\"port\":6379,\"sslPort\":6380}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '653',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  location: 'https://prod-rp-wus.cacheinfra.windows.net:10225/subscriptions/04db7ed3-6ed9-4861-8b22-7c0c0c98490b/resourceGroups/xplatTestCacheRG/providers/Microsoft.Cache/Redis/xplatTestCache2861',
  'x-ms-request-id': 'c7cac79d-667a-4d0a-b1be-6fe175ad7a3d',
  'x-rp-server-mvid': 'af670903-1b42-4933-b84c-636f2d204d89',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-writes': '1197',
  'x-ms-correlation-request-id': 'ee1c0c18-b83e-4351-a5a0-bb9b2a02fa6b',
  'x-ms-routing-request-id': 'WESTUS:20150820T002333Z:ee1c0c18-b83e-4351-a5a0-bb9b2a02fa6b',
  date: 'Thu, 20 Aug 2015 00:23:33 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/04db7ed3-6ed9-4861-8b22-7c0c0c98490b/resourceGroups/xplatTestCacheRG/providers/Microsoft.Cache/Redis/xplatTestCache938?api-version=2015-03-01')
  .reply(404, "{\"error\":{\"code\":\"ResourceNotFound\",\"message\":\"The Resource 'Microsoft.Cache/Redis/xplatTestCache938' under resource group 'xplatTestCacheRG' was not found.\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-failure-cause': 'gateway',
  'x-ms-request-id': '890cdb4e-4d71-409f-8e27-05fec7a8f760',
  'x-ms-correlation-request-id': '890cdb4e-4d71-409f-8e27-05fec7a8f760',
  'x-ms-routing-request-id': 'WESTUS:20150820T002334Z:890cdb4e-4d71-409f-8e27-05fec7a8f760',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Thu, 20 Aug 2015 00:23:33 GMT',
  connection: 'close',
  'content-length': '159' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/04db7ed3-6ed9-4861-8b22-7c0c0c98490b/resourceGroups/xplatTestCacheRG/providers/Microsoft.Cache/Redis/xplatTestCache938?api-version=2015-03-01')
  .reply(404, "{\"error\":{\"code\":\"ResourceNotFound\",\"message\":\"The Resource 'Microsoft.Cache/Redis/xplatTestCache938' under resource group 'xplatTestCacheRG' was not found.\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-failure-cause': 'gateway',
  'x-ms-request-id': '890cdb4e-4d71-409f-8e27-05fec7a8f760',
  'x-ms-correlation-request-id': '890cdb4e-4d71-409f-8e27-05fec7a8f760',
  'x-ms-routing-request-id': 'WESTUS:20150820T002334Z:890cdb4e-4d71-409f-8e27-05fec7a8f760',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Thu, 20 Aug 2015 00:23:33 GMT',
  connection: 'close',
  'content-length': '159' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/04db7ed3-6ed9-4861-8b22-7c0c0c98490b/resourceGroups/xplatTestCacheRG/providers/Microsoft.Cache/Redis/xplatTestCache938?api-version=2015-03-01', '*')
  .reply(201, "{\"id\":\"/subscriptions/04db7ed3-6ed9-4861-8b22-7c0c0c98490b/resourceGroups/xplatTestCacheRG/providers/Microsoft.Cache/Redis/xplatTestCache938\",\"location\":\"West US\",\"name\":\"xplatTestCache938\",\"type\":\"Microsoft.Cache/Redis\",\"tags\":{},\"properties\":{\"provisioningState\":\"Creating\",\"redisVersion\":\"3.0\",\"sku\":{\"name\":\"Basic\",\"family\":\"C\",\"capacity\":2},\"enableNonSslPort\":true,\"redisConfiguration\":{\"maxmemory-policy\":\"allkeys-random\"},\"accessKeys\":{\"primaryKey\":\"BxKGAgptW+Sw6f5scVEwOMqR7wR+BdzLHpYmJShd5Zk=\",\"secondaryKey\":\"ebovzbgEXFtHDiv0YN2RHPYM0ZBAqj7bVGvude4Johk=\"},\"hostName\":\"xplatTestCache938.redis.cache.windows.net\",\"port\":6379,\"sslPort\":6380}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '649',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  location: 'https://prod-rp-wus.cacheinfra.windows.net:10225/subscriptions/04db7ed3-6ed9-4861-8b22-7c0c0c98490b/resourceGroups/xplatTestCacheRG/providers/Microsoft.Cache/Redis/xplatTestCache938',
  'x-ms-request-id': '8d037f22-cf0e-4f36-b05a-10fadb2d82dd',
  'x-rp-server-mvid': 'af670903-1b42-4933-b84c-636f2d204d89',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-writes': '1197',
  'x-ms-correlation-request-id': 'b35112d4-c1f6-4145-9884-e5559d75cf7b',
  'x-ms-routing-request-id': 'WESTUS:20150820T002335Z:b35112d4-c1f6-4145-9884-e5559d75cf7b',
  date: 'Thu, 20 Aug 2015 00:23:34 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/04db7ed3-6ed9-4861-8b22-7c0c0c98490b/resourceGroups/xplatTestCacheRG/providers/Microsoft.Cache/Redis/xplatTestCache938?api-version=2015-03-01', '*')
  .reply(201, "{\"id\":\"/subscriptions/04db7ed3-6ed9-4861-8b22-7c0c0c98490b/resourceGroups/xplatTestCacheRG/providers/Microsoft.Cache/Redis/xplatTestCache938\",\"location\":\"West US\",\"name\":\"xplatTestCache938\",\"type\":\"Microsoft.Cache/Redis\",\"tags\":{},\"properties\":{\"provisioningState\":\"Creating\",\"redisVersion\":\"3.0\",\"sku\":{\"name\":\"Basic\",\"family\":\"C\",\"capacity\":2},\"enableNonSslPort\":true,\"redisConfiguration\":{\"maxmemory-policy\":\"allkeys-random\"},\"accessKeys\":{\"primaryKey\":\"BxKGAgptW+Sw6f5scVEwOMqR7wR+BdzLHpYmJShd5Zk=\",\"secondaryKey\":\"ebovzbgEXFtHDiv0YN2RHPYM0ZBAqj7bVGvude4Johk=\"},\"hostName\":\"xplatTestCache938.redis.cache.windows.net\",\"port\":6379,\"sslPort\":6380}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '649',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  location: 'https://prod-rp-wus.cacheinfra.windows.net:10225/subscriptions/04db7ed3-6ed9-4861-8b22-7c0c0c98490b/resourceGroups/xplatTestCacheRG/providers/Microsoft.Cache/Redis/xplatTestCache938',
  'x-ms-request-id': '8d037f22-cf0e-4f36-b05a-10fadb2d82dd',
  'x-rp-server-mvid': 'af670903-1b42-4933-b84c-636f2d204d89',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-writes': '1197',
  'x-ms-correlation-request-id': 'b35112d4-c1f6-4145-9884-e5559d75cf7b',
  'x-ms-routing-request-id': 'WESTUS:20150820T002335Z:b35112d4-c1f6-4145-9884-e5559d75cf7b',
  date: 'Thu, 20 Aug 2015 00:23:34 GMT',
  connection: 'close' });
 return result; }]];