// This file has been autogenerated.

var profile = require('../../../lib/util/profile');

exports.getMockedProfile = function () {
  var newProfile = new profile.Profile();

  newProfile.addSubscription(new profile.Subscription({
    id: '2c224e7e-3ef5-431d-a57b-e71f4662e3a6',
    name: 'Node CLI Test',
    user: {
      name: 'user@domain.example',
      type: 'user'
    },
    tenantId: '72f988bf-86f1-41af-91ab-2d7cd011db47',
    state: 'Enabled',
    registeredProviders: [],
    _eventsCount: '1',
    isDefault: true
  }, newProfile.environments['AzureCloud']));

  return newProfile;
};

exports.setEnvironment = function() {
  process.env['AZURE_VM_TEST_LOCATION'] = 'westus';
};

exports.scopes = [[function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/2c224e7e-3ef5-431d-a57b-e71f4662e3a6/resourceGroups/xplat-test-public-ip/providers/Microsoft.Network/publicIPAddresses/publicIPAddressesDefaultName?api-version=2017-03-01')
  .reply(404, "{\"error\":{\"code\":\"ResourceNotFound\",\"message\":\"The Resource 'Microsoft.Network/publicIPAddresses/publicIPAddressesDefaultName' under resource group 'xplat-test-public-ip' was not found.\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-failure-cause': 'gateway',
  'x-ms-request-id': '2fadd123-2044-4ded-a492-47fbdff9e34e',
  'x-ms-correlation-request-id': '2fadd123-2044-4ded-a492-47fbdff9e34e',
  'x-ms-routing-request-id': 'WESTEUROPE:20170525T122703Z:2fadd123-2044-4ded-a492-47fbdff9e34e',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Thu, 25 May 2017 12:27:02 GMT',
  connection: 'close',
  'content-length': '188' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/2c224e7e-3ef5-431d-a57b-e71f4662e3a6/resourceGroups/xplat-test-public-ip/providers/Microsoft.Network/publicIPAddresses/publicIPAddressesDefaultName?api-version=2017-03-01')
  .reply(404, "{\"error\":{\"code\":\"ResourceNotFound\",\"message\":\"The Resource 'Microsoft.Network/publicIPAddresses/publicIPAddressesDefaultName' under resource group 'xplat-test-public-ip' was not found.\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-failure-cause': 'gateway',
  'x-ms-request-id': '2fadd123-2044-4ded-a492-47fbdff9e34e',
  'x-ms-correlation-request-id': '2fadd123-2044-4ded-a492-47fbdff9e34e',
  'x-ms-routing-request-id': 'WESTEUROPE:20170525T122703Z:2fadd123-2044-4ded-a492-47fbdff9e34e',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Thu, 25 May 2017 12:27:02 GMT',
  connection: 'close',
  'content-length': '188' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/2c224e7e-3ef5-431d-a57b-e71f4662e3a6/resourceGroups/xplat-test-public-ip/providers/Microsoft.Network/publicIPAddresses/publicIPAddressesDefaultName?api-version=2017-03-01', '*')
  .reply(201, "{\r\n  \"name\": \"publicIPAddressesDefaultName\",\r\n  \"id\": \"/subscriptions/2c224e7e-3ef5-431d-a57b-e71f4662e3a6/resourceGroups/xplat-test-public-ip/providers/Microsoft.Network/publicIPAddresses/publicIPAddressesDefaultName\",\r\n  \"etag\": \"W/\\\"568ed867-485a-4490-b994-504da262a33a\\\"\",\r\n  \"location\": \"westus\",\r\n  \"properties\": {\r\n    \"provisioningState\": \"Updating\",\r\n    \"resourceGuid\": \"4c86831c-a527-41e5-abad-507604248428\",\r\n    \"publicIPAddressVersion\": \"IPv4\",\r\n    \"publicIPAllocationMethod\": \"Dynamic\",\r\n    \"idleTimeoutInMinutes\": 4\r\n  },\r\n  \"type\": \"Microsoft.Network/publicIPAddresses\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '591',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'retry-after': '3',
  'x-ms-request-id': 'd80b542a-d0f9-420e-a489-ad29f75068ed',
  'azure-asyncoperation': 'https://management.azure.com/subscriptions/2c224e7e-3ef5-431d-a57b-e71f4662e3a6/providers/Microsoft.Network/locations/westus.validation/operations/d80b542a-d0f9-420e-a489-ad29f75068ed?api-version=2017-03-01',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-writes': '1199',
  'x-ms-correlation-request-id': '13e2949f-3b77-456a-9ccc-4cea58a2bd67',
  'x-ms-routing-request-id': 'WESTEUROPE:20170525T122707Z:13e2949f-3b77-456a-9ccc-4cea58a2bd67',
  date: 'Thu, 25 May 2017 12:27:07 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/2c224e7e-3ef5-431d-a57b-e71f4662e3a6/resourceGroups/xplat-test-public-ip/providers/Microsoft.Network/publicIPAddresses/publicIPAddressesDefaultName?api-version=2017-03-01', '*')
  .reply(201, "{\r\n  \"name\": \"publicIPAddressesDefaultName\",\r\n  \"id\": \"/subscriptions/2c224e7e-3ef5-431d-a57b-e71f4662e3a6/resourceGroups/xplat-test-public-ip/providers/Microsoft.Network/publicIPAddresses/publicIPAddressesDefaultName\",\r\n  \"etag\": \"W/\\\"568ed867-485a-4490-b994-504da262a33a\\\"\",\r\n  \"location\": \"westus\",\r\n  \"properties\": {\r\n    \"provisioningState\": \"Updating\",\r\n    \"resourceGuid\": \"4c86831c-a527-41e5-abad-507604248428\",\r\n    \"publicIPAddressVersion\": \"IPv4\",\r\n    \"publicIPAllocationMethod\": \"Dynamic\",\r\n    \"idleTimeoutInMinutes\": 4\r\n  },\r\n  \"type\": \"Microsoft.Network/publicIPAddresses\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '591',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'retry-after': '3',
  'x-ms-request-id': 'd80b542a-d0f9-420e-a489-ad29f75068ed',
  'azure-asyncoperation': 'https://management.azure.com/subscriptions/2c224e7e-3ef5-431d-a57b-e71f4662e3a6/providers/Microsoft.Network/locations/westus.validation/operations/d80b542a-d0f9-420e-a489-ad29f75068ed?api-version=2017-03-01',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-writes': '1199',
  'x-ms-correlation-request-id': '13e2949f-3b77-456a-9ccc-4cea58a2bd67',
  'x-ms-routing-request-id': 'WESTEUROPE:20170525T122707Z:13e2949f-3b77-456a-9ccc-4cea58a2bd67',
  date: 'Thu, 25 May 2017 12:27:07 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/2c224e7e-3ef5-431d-a57b-e71f4662e3a6/providers/Microsoft.Network/locations/westus.validation/operations/d80b542a-d0f9-420e-a489-ad29f75068ed?api-version=2017-03-01')
  .reply(200, "{\r\n  \"status\": \"Succeeded\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '29',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': '8b80a095-f7c9-456e-a01a-7139f6a40144',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14997',
  'x-ms-correlation-request-id': '48a2f524-4487-4111-a618-b83f6f5a54aa',
  'x-ms-routing-request-id': 'WESTEUROPE:20170525T122739Z:48a2f524-4487-4111-a618-b83f6f5a54aa',
  date: 'Thu, 25 May 2017 12:27:38 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/2c224e7e-3ef5-431d-a57b-e71f4662e3a6/providers/Microsoft.Network/locations/westus.validation/operations/d80b542a-d0f9-420e-a489-ad29f75068ed?api-version=2017-03-01')
  .reply(200, "{\r\n  \"status\": \"Succeeded\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '29',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': '8b80a095-f7c9-456e-a01a-7139f6a40144',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14997',
  'x-ms-correlation-request-id': '48a2f524-4487-4111-a618-b83f6f5a54aa',
  'x-ms-routing-request-id': 'WESTEUROPE:20170525T122739Z:48a2f524-4487-4111-a618-b83f6f5a54aa',
  date: 'Thu, 25 May 2017 12:27:38 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/2c224e7e-3ef5-431d-a57b-e71f4662e3a6/resourceGroups/xplat-test-public-ip/providers/Microsoft.Network/publicIPAddresses/publicIPAddressesDefaultName?api-version=2017-03-01')
  .reply(200, "{\r\n  \"name\": \"publicIPAddressesDefaultName\",\r\n  \"id\": \"/subscriptions/2c224e7e-3ef5-431d-a57b-e71f4662e3a6/resourceGroups/xplat-test-public-ip/providers/Microsoft.Network/publicIPAddresses/publicIPAddressesDefaultName\",\r\n  \"etag\": \"W/\\\"4d2f9a38-f8ed-44f2-a381-3aac8e1c33f8\\\"\",\r\n  \"location\": \"westus\",\r\n  \"properties\": {\r\n    \"provisioningState\": \"Succeeded\",\r\n    \"resourceGuid\": \"4c86831c-a527-41e5-abad-507604248428\",\r\n    \"publicIPAddressVersion\": \"IPv4\",\r\n    \"publicIPAllocationMethod\": \"Dynamic\",\r\n    \"idleTimeoutInMinutes\": 4\r\n  },\r\n  \"type\": \"Microsoft.Network/publicIPAddresses\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '592',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  etag: 'W/"4d2f9a38-f8ed-44f2-a381-3aac8e1c33f8"',
  'x-ms-request-id': 'd9833a95-d1e2-4b11-823a-07757255bc50',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14965',
  'x-ms-correlation-request-id': '06e452f1-f112-4cd9-849d-5e04b41ffc95',
  'x-ms-routing-request-id': 'WESTEUROPE:20170525T122740Z:06e452f1-f112-4cd9-849d-5e04b41ffc95',
  date: 'Thu, 25 May 2017 12:27:39 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/2c224e7e-3ef5-431d-a57b-e71f4662e3a6/resourceGroups/xplat-test-public-ip/providers/Microsoft.Network/publicIPAddresses/publicIPAddressesDefaultName?api-version=2017-03-01')
  .reply(200, "{\r\n  \"name\": \"publicIPAddressesDefaultName\",\r\n  \"id\": \"/subscriptions/2c224e7e-3ef5-431d-a57b-e71f4662e3a6/resourceGroups/xplat-test-public-ip/providers/Microsoft.Network/publicIPAddresses/publicIPAddressesDefaultName\",\r\n  \"etag\": \"W/\\\"4d2f9a38-f8ed-44f2-a381-3aac8e1c33f8\\\"\",\r\n  \"location\": \"westus\",\r\n  \"properties\": {\r\n    \"provisioningState\": \"Succeeded\",\r\n    \"resourceGuid\": \"4c86831c-a527-41e5-abad-507604248428\",\r\n    \"publicIPAddressVersion\": \"IPv4\",\r\n    \"publicIPAllocationMethod\": \"Dynamic\",\r\n    \"idleTimeoutInMinutes\": 4\r\n  },\r\n  \"type\": \"Microsoft.Network/publicIPAddresses\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '592',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  etag: 'W/"4d2f9a38-f8ed-44f2-a381-3aac8e1c33f8"',
  'x-ms-request-id': 'd9833a95-d1e2-4b11-823a-07757255bc50',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14965',
  'x-ms-correlation-request-id': '06e452f1-f112-4cd9-849d-5e04b41ffc95',
  'x-ms-routing-request-id': 'WESTEUROPE:20170525T122740Z:06e452f1-f112-4cd9-849d-5e04b41ffc95',
  date: 'Thu, 25 May 2017 12:27:39 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/2c224e7e-3ef5-431d-a57b-e71f4662e3a6/resourceGroups/xplat-test-public-ip/providers/Microsoft.Network/publicIPAddresses/publicIPAddressesDefaultName?api-version=2017-03-01')
  .reply(200, "{\r\n  \"name\": \"publicIPAddressesDefaultName\",\r\n  \"id\": \"/subscriptions/2c224e7e-3ef5-431d-a57b-e71f4662e3a6/resourceGroups/xplat-test-public-ip/providers/Microsoft.Network/publicIPAddresses/publicIPAddressesDefaultName\",\r\n  \"etag\": \"W/\\\"4d2f9a38-f8ed-44f2-a381-3aac8e1c33f8\\\"\",\r\n  \"location\": \"westus\",\r\n  \"properties\": {\r\n    \"provisioningState\": \"Succeeded\",\r\n    \"resourceGuid\": \"4c86831c-a527-41e5-abad-507604248428\",\r\n    \"publicIPAddressVersion\": \"IPv4\",\r\n    \"publicIPAllocationMethod\": \"Dynamic\",\r\n    \"idleTimeoutInMinutes\": 4\r\n  },\r\n  \"type\": \"Microsoft.Network/publicIPAddresses\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '592',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  etag: 'W/"4d2f9a38-f8ed-44f2-a381-3aac8e1c33f8"',
  'x-ms-request-id': 'dac69e88-edba-43b7-b76c-aeda63d13903',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14965',
  'x-ms-correlation-request-id': '8d243aa6-50b8-4588-8e05-897ff6338e35',
  'x-ms-routing-request-id': 'WESTEUROPE:20170525T122741Z:8d243aa6-50b8-4588-8e05-897ff6338e35',
  date: 'Thu, 25 May 2017 12:27:40 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/2c224e7e-3ef5-431d-a57b-e71f4662e3a6/resourceGroups/xplat-test-public-ip/providers/Microsoft.Network/publicIPAddresses/publicIPAddressesDefaultName?api-version=2017-03-01')
  .reply(200, "{\r\n  \"name\": \"publicIPAddressesDefaultName\",\r\n  \"id\": \"/subscriptions/2c224e7e-3ef5-431d-a57b-e71f4662e3a6/resourceGroups/xplat-test-public-ip/providers/Microsoft.Network/publicIPAddresses/publicIPAddressesDefaultName\",\r\n  \"etag\": \"W/\\\"4d2f9a38-f8ed-44f2-a381-3aac8e1c33f8\\\"\",\r\n  \"location\": \"westus\",\r\n  \"properties\": {\r\n    \"provisioningState\": \"Succeeded\",\r\n    \"resourceGuid\": \"4c86831c-a527-41e5-abad-507604248428\",\r\n    \"publicIPAddressVersion\": \"IPv4\",\r\n    \"publicIPAllocationMethod\": \"Dynamic\",\r\n    \"idleTimeoutInMinutes\": 4\r\n  },\r\n  \"type\": \"Microsoft.Network/publicIPAddresses\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '592',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  etag: 'W/"4d2f9a38-f8ed-44f2-a381-3aac8e1c33f8"',
  'x-ms-request-id': 'dac69e88-edba-43b7-b76c-aeda63d13903',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14965',
  'x-ms-correlation-request-id': '8d243aa6-50b8-4588-8e05-897ff6338e35',
  'x-ms-routing-request-id': 'WESTEUROPE:20170525T122741Z:8d243aa6-50b8-4588-8e05-897ff6338e35',
  date: 'Thu, 25 May 2017 12:27:40 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .delete('/subscriptions/2c224e7e-3ef5-431d-a57b-e71f4662e3a6/resourceGroups/xplat-test-public-ip/providers/Microsoft.Network/publicIPAddresses/publicIPAddressesDefaultName?api-version=2017-03-01')
  .reply(202, "", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '0',
  expires: '-1',
  location: 'https://management.azure.com/subscriptions/2c224e7e-3ef5-431d-a57b-e71f4662e3a6/providers/Microsoft.Network/locations/westus.validation/operationResults/55ea611f-94e2-40b2-bff9-5044ce6c0718?api-version=2017-03-01',
  'retry-after': '10',
  'x-ms-request-id': '55ea611f-94e2-40b2-bff9-5044ce6c0718',
  'azure-asyncoperation': 'https://management.azure.com/subscriptions/2c224e7e-3ef5-431d-a57b-e71f4662e3a6/providers/Microsoft.Network/locations/westus.validation/operations/55ea611f-94e2-40b2-bff9-5044ce6c0718?api-version=2017-03-01',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-writes': '1199',
  'x-ms-correlation-request-id': 'd258c388-ccf4-4256-aae7-909eef86d553',
  'x-ms-routing-request-id': 'WESTEUROPE:20170525T122744Z:d258c388-ccf4-4256-aae7-909eef86d553',
  date: 'Thu, 25 May 2017 12:27:43 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .delete('/subscriptions/2c224e7e-3ef5-431d-a57b-e71f4662e3a6/resourceGroups/xplat-test-public-ip/providers/Microsoft.Network/publicIPAddresses/publicIPAddressesDefaultName?api-version=2017-03-01')
  .reply(202, "", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '0',
  expires: '-1',
  location: 'https://management.azure.com/subscriptions/2c224e7e-3ef5-431d-a57b-e71f4662e3a6/providers/Microsoft.Network/locations/westus.validation/operationResults/55ea611f-94e2-40b2-bff9-5044ce6c0718?api-version=2017-03-01',
  'retry-after': '10',
  'x-ms-request-id': '55ea611f-94e2-40b2-bff9-5044ce6c0718',
  'azure-asyncoperation': 'https://management.azure.com/subscriptions/2c224e7e-3ef5-431d-a57b-e71f4662e3a6/providers/Microsoft.Network/locations/westus.validation/operations/55ea611f-94e2-40b2-bff9-5044ce6c0718?api-version=2017-03-01',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-writes': '1199',
  'x-ms-correlation-request-id': 'd258c388-ccf4-4256-aae7-909eef86d553',
  'x-ms-routing-request-id': 'WESTEUROPE:20170525T122744Z:d258c388-ccf4-4256-aae7-909eef86d553',
  date: 'Thu, 25 May 2017 12:27:43 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/2c224e7e-3ef5-431d-a57b-e71f4662e3a6/providers/Microsoft.Network/locations/westus.validation/operations/55ea611f-94e2-40b2-bff9-5044ce6c0718?api-version=2017-03-01')
  .reply(200, "{\r\n  \"status\": \"Succeeded\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '29',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': 'fce17206-fd13-43ad-b585-826dfc748b03',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14999',
  'x-ms-correlation-request-id': '2b41cb1a-5d32-4eed-b0ef-eae75567e08d',
  'x-ms-routing-request-id': 'WESTEUROPE:20170525T122815Z:2b41cb1a-5d32-4eed-b0ef-eae75567e08d',
  date: 'Thu, 25 May 2017 12:28:14 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/2c224e7e-3ef5-431d-a57b-e71f4662e3a6/providers/Microsoft.Network/locations/westus.validation/operations/55ea611f-94e2-40b2-bff9-5044ce6c0718?api-version=2017-03-01')
  .reply(200, "{\r\n  \"status\": \"Succeeded\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '29',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': 'fce17206-fd13-43ad-b585-826dfc748b03',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14999',
  'x-ms-correlation-request-id': '2b41cb1a-5d32-4eed-b0ef-eae75567e08d',
  'x-ms-routing-request-id': 'WESTEUROPE:20170525T122815Z:2b41cb1a-5d32-4eed-b0ef-eae75567e08d',
  date: 'Thu, 25 May 2017 12:28:14 GMT',
  connection: 'close' });
 return result; }]];